spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    repositories.enabled: true
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgresDialect
      properties.hibernate.event.merge.entity_copy_observer: allow

rest:
  marvel:
    host: gateway.marvel.com/v1/public
    limit: 100
    key:
      public: ${MARVEL_PUBLIC_KEY}
      private: ${MARVEL_PRIVATE_KEY}

  cron.expression: ${0 0 0 * * *}